#!/bin/bash
# ============================================================
#  Planaro Meet — LiveKit Server Setup
#  VPS: 85.198.71.231  |  Domain: meet.planaro.ru
#  OS: Ubuntu 24.04
#
#  Run as root:  bash setup-livekit.sh
# ============================================================
set -euo pipefail

DOMAIN="meet.planaro.ru"

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║   Planaro Meet — LiveKit Server Setup            ║"
echo "║   Domain: ${DOMAIN}                    ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""

# ── 1. Generate API credentials ──────────────────────────────────────────────
API_KEY="APIplanaro$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 10)"
API_SECRET="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 48)"

echo "✅ Generated LiveKit API credentials:"
echo "   LIVEKIT_API_KEY    = $API_KEY"
echo "   LIVEKIT_API_SECRET = $API_SECRET"
echo ""
echo "⚠️  COPY THESE NOW — you'll need them for Supabase secrets!"
echo ""

# ── 2. System update ──────────────────────────────────────────────────────────
echo "📦 Updating system packages..."
apt-get update -y -q
apt-get install -y -q curl wget tar ufw

# ── 3. Install Caddy (auto HTTPS) ────────────────────────────────────────────
echo "🌐 Installing Caddy..."
apt-get install -y -q debian-keyring debian-archive-keyring apt-transport-https gnupg
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
  | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
  | tee /etc/apt/sources.list.d/caddy-stable.list
apt-get update -y -q
apt-get install -y -q caddy
echo "✅ Caddy installed"

# ── 4. Install LiveKit Server ─────────────────────────────────────────────────
echo "🎥 Installing LiveKit Server..."
LK_TAG=$(curl -s https://api.github.com/repos/livekit/livekit/releases/latest \
  | grep '"tag_name"' | cut -d'"' -f4)
LK_VER="${LK_TAG#v}"
echo "   Version: $LK_VER"

curl -sL "https://github.com/livekit/livekit/releases/download/${LK_TAG}/livekit_${LK_VER}_linux_amd64.tar.gz" \
  | tar xz -C /tmp
mv /tmp/livekit-server /usr/local/bin/livekit-server
chmod +x /usr/local/bin/livekit-server
echo "✅ LiveKit $LK_VER installed at /usr/local/bin/livekit-server"

# ── 5. LiveKit config ─────────────────────────────────────────────────────────
echo "⚙️  Writing LiveKit config..."
mkdir -p /etc/livekit

cat > /etc/livekit/livekit.yaml << EOF
# LiveKit Server Configuration — Planaro Meet
# Auto-generated by setup-livekit.sh

port: 7880
bind_addresses:
  - ""

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true
  enable_loopback_candidate: false

# API keys — keep secret!
keys:
  ${API_KEY}: ${API_SECRET}

logging:
  level: info
  pion_level: error
EOF

echo "✅ Config written to /etc/livekit/livekit.yaml"

# ── 6. Caddyfile ──────────────────────────────────────────────────────────────
echo "⚙️  Writing Caddyfile..."
cat > /etc/caddy/Caddyfile << EOF
${DOMAIN} {
    # Reverse proxy to LiveKit (handles HTTP API + WebSocket signaling)
    reverse_proxy localhost:7880 {
        header_up Host {host}
        header_up X-Real-IP {remote_host}
        header_up X-Forwarded-For {remote_host}
        header_up X-Forwarded-Proto {scheme}
    }
}
EOF

echo "✅ Caddyfile written to /etc/caddy/Caddyfile"

# ── 7. Systemd service for LiveKit ───────────────────────────────────────────
echo "⚙️  Creating systemd service..."
cat > /etc/systemd/system/livekit.service << 'EOF'
[Unit]
Description=LiveKit SFU Server — Planaro Meet
Documentation=https://docs.livekit.io
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
ExecStart=/usr/local/bin/livekit-server --config /etc/livekit/livekit.yaml
Restart=on-failure
RestartSec=5
LimitNOFILE=500000

[Install]
WantedBy=multi-user.target
EOF

echo "✅ Systemd service created"

# ── 8. Firewall (ufw) ─────────────────────────────────────────────────────────
echo "🔒 Configuring firewall..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw allow 80/tcp   comment "HTTP (Let's Encrypt)"
ufw allow 443/tcp  comment "HTTPS / WSS (Caddy)"
ufw allow 7881/tcp comment "LiveKit RTC TCP fallback"
ufw allow 50000:60000/udp comment "LiveKit RTC UDP media"
ufw --force enable
echo "✅ Firewall configured"

# ── 9. Start services ─────────────────────────────────────────────────────────
echo "🚀 Starting services..."
systemctl daemon-reload
systemctl enable livekit
systemctl start livekit

systemctl enable caddy
systemctl reload-or-restart caddy

sleep 3

LIVEKIT_STATUS=$(systemctl is-active livekit 2>/dev/null || echo "failed")
CADDY_STATUS=$(systemctl is-active caddy 2>/dev/null || echo "failed")

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                    SETUP COMPLETE ✅                         ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  LiveKit:  ${LIVEKIT_STATUS}                                        ║"
echo "║  Caddy:    ${CADDY_STATUS}                                          ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  Add these to Supabase Dashboard → Settings → Edge Function  ║"
echo "║  Secrets (or via: supabase secrets set KEY=value):           ║"
echo "║                                                              ║"
echo "║  LIVEKIT_API_KEY    = ${API_KEY}       ║"
echo "║  LIVEKIT_API_SECRET = ${API_SECRET:0:20}...  ║"
echo "║  LIVEKIT_URL        = wss://${DOMAIN}    ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  Useful commands:                                            ║"
echo "║    systemctl status livekit                                  ║"
echo "║    journalctl -u livekit -f                                  ║"
echo "║    systemctl status caddy                                    ║"
echo "║    journalctl -u caddy -f                                    ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "Full credentials (save these!):"
echo "LIVEKIT_API_KEY=$API_KEY"
echo "LIVEKIT_API_SECRET=$API_SECRET"
echo "LIVEKIT_URL=wss://${DOMAIN}"
